import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const eslintConfig = [
  // next-env.d.ts is generated by Next and contains its required triple-slash references.
  { ignores: ['node_modules/**', '.next/**', 'out/**', 'public/_local-data/**', 'release/**', 'next-env.d.ts'] },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default eslintConfig;
